name: medical_assistant
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_custom_clippers: ^2.0.0
  firebase_storage: ^10.2.13
  file_picker: ^4.5.1
  geocoding: ^2.0.4
  wakelock: ^0.6.1+2
  camera: ^0.9.4+19
  path_provider: ^2.0.9
  velocity_x: ^3.4.0
  syncfusion_flutter_charts: ^20.1.48
  rxdart: ^0.27.2
  oktoast: ^3.1.5
  permission_handler: ^9.2.0
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  flutter_staggered_animations: ^1.0.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  bubble_tab_indicator: ^0.1.6
  http: ^0.13.4
  provider: ^6.0.2
  webview_flutter: ^3.0.2
  curved_navigation_bar: ^1.0.3
  page_transition: ^2.0.5
  google_maps_flutter: ^2.1.3
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.0
  local_auth: ^1.1.11
  carousel_slider: ^4.0.0
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_png.png"
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Candara
      fonts:
        - asset: assets/fonts/candara-bold.ttf
          weight: 700
        - asset: assets/fonts/candara-normal.ttf
        - asset: assets/fonts/candara-italic.ttf
          style: italic
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
